services:
  db:
    image: mysql:8.0
    container_name: db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/mysql_root_password
      MYSQL_DATABASE: idade_db
      MYSQL_USER: usuario
      MYSQL_PASSWORD_FILE: /run/secrets/mysql_password
    volumes:
      - db-data-idade:/var/lib/mysql
      - ./secrets/mysql_root_password.txt:/run/secrets/mysql_root_password:ro
      - ./secrets/mysql_password.txt:/run/secrets/mysql_password:ro
    networks:
      - idade-network

  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    restart: always
    environment:
      DB_HOST: db
      DB_USER: usuario
      DB_NAME: idade_db
    secrets:
      - mysql_password
    depends_on:
      - db
    ports:
      - "5000:5000"
    networks:
      - idade-network

  frontend:
    build: ./frontend
    container_name: frontend
    restart: always
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - idade-network

volumes:
  db-data-idade:

secrets:
  mysql_root_password:
    file: ./secrets/mysql_root_password.txt
  mysql_password:
    file: ./secrets/mysql_password.txt

networks:
  idade-network:
    driver: bridge
